### ISSUE TITLE
Create a raw repository in Nexus

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#13]
**Description:**
As a developer, I want to store any binary files into a shared repository that allows people and pipelines to download them, update them and so on.

**Acceptance Criteria:**
- The binaries of both ConverterService and MLService should be uploaded to this repo.
- The binaries should be downloaded by using the command `curl`.
- The repo should be created manually, not neede to use a pipeline.

**Dependency:**
No dependencies.

**Comment by Rei-Fer** [comment]
- The binaries of MLService were uploaded to the repository "at-raw" 
![Image](https://github.com/user-attachments/assets/d489787e-130f-4a25-806e-e7e8d110c199)

- The binaries of MLService can be downloaded using the curl command
![Image](https://github.com/user-attachments/assets/e5fa0dc7-9a3b-4fd6-9d63-a5d756b53195)

**Comment by Rei-Fer** [comment]
- The binaries of ConverterService were uploaded to the repository "at-raw"
![Image](https://github.com/user-attachments/assets/5a13993e-3a50-4578-88e5-d40bbc04ce1f)

**Comment by Rei-Fer** [comment]
**@calebespinoza**
**Tasks completed:**

- The binaries of both ConverterService and MLService are uploaded in "at-raw".
![Image](https://github.com/user-attachments/assets/9a29a2a9-4932-4579-be58-4ed9236d79c5)

- The binaries can be downloaded by using the command curl.
![Image](https://github.com/user-attachments/assets/6dffc197-c673-48dd-b092-78ea059469cf)

- And the repo doesn't use a pipeline.
