### ISSUE TITLE
Deploy a Nexus service

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#2]
As an operator, I need to have a Binary repository server to store any artifacts such as container images, videos, images, icons, etc.

**Acceptance Criteria:**
- A Nexus container should be deployed via Ansible.
- Only the Dev Server should host the Nexus container:
- Nexus Web UI should be accessed in this URL: https://nexus.at04.devops.jala.university
- The container port of Nexus should be exposed in 8081/tcp
- Make sure to use the official Docker image https://hub.docker.com/r/sonatype/nexus3

**Dependency:**
This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/1

**Supporting docs:**
- https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html

**Comment by michelle-gh** [comment]
- The tasks to create the nexus container in the development server via ansible have been added.
- The container uses a volume nexus-data to make data persistent and exposes the port 8081 to access the Nexus Web UI in the URL: https://nexus.at04.devops.jala.university/
