### ISSUE TITLE
Add insecure registry into both dev and prod servers

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#21]
**Description:**
As an operator, I need to add our registry as insecure in our both servers to perform deployments.

**Acceptance Criteria:**
- A file daemon.json should be created in `/etc/docker` at both Development and Production servers.
- The file daemon.json should contain the insecure registry `registry.at04.devops.jala.university`
- The docker login should be tested (could be manually or automatically).

**Dependency:**
No dependencies

**Comment by Rei-Fer** [comment]
**@calebespinoza
Tasks completed:**
- A file daemon.json was created in /etc/docker on both the Development and Production servers.
![Image](https://github.com/user-attachments/assets/dc67dc62-f88b-4ac4-9013-2a3d6d48b93c)
- The file daemon.json contains the insecure registry registry.at04.devops.jala.university
![Image](https://github.com/user-attachments/assets/027d0f9b-226a-4cde-9253-68c9a9db7a8a)
- The docker login was tested manually 
![Image](https://github.com/user-attachments/assets/7499fc71-0adc-4c09-afff-ee25565b9a27)

**Comment by Rei-Fer** [comment]
@calebespinoza the suggested changes were made for ovoid ansible-lint errors
