### ISSUE TITLE
Implement User Acceptance Testing for MLService

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#24]
**Description:**
As a QA, I need to run User Acceptance tests to certify if the new version of MLService is production-ready.

**Acceptance Criteria:**
- The UA tests should be run after the deployment into Dev server
- All the UA test should be using `curl` to retrieve the HTTP Code 200
- Every endpoint should be tested to retrieve the HTTP Code 200.
- These tests should be executed automatically in a pipeline.

**Dependency:**
This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/22

**Comment by calebespinoza** [comment]
Command:
```bash
curl -s -o /dev/null -w "%{http_code}" https://dev-mlservice.devops.jala.university/path/to/each/endpoint | jq -R .
```
Output:
```bash
"200"
```

**Comment by GDayne** [comment]
- [ ] Create the script in test package inside MLservice
- [ ] Call the script in the MLservice ci pipeline

**Comment by GDayne** [comment]
Endpoints used:
![Image](https://github.com/user-attachments/assets/87ee9120-8cfd-485b-a971-f4453e6d9ad0)
