### ISSUE TITLE
Update endpoints in desktop UI app

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#38]
**Description:**

As preparing for our Demo to show ConverterService and MLService working, we need to have the Desktop UI app pointing out to their endpoints.

**Acceptance Criteria:**
- The Desktop UI app should work by consuming endpoints deployed in Production (preferable).

**Aclaration:**
This Working Item doesn't belong to ConfigManage repo, so, nothing to add in the source code. Just show us that it works as expected before de demo to mark it as Done.

**Comment by Eynar92** [comment]
Updated the desktop UI App

![Image](https://github.com/user-attachments/assets/04e86d2a-02a1-4452-a592-47c9c07b8dc2)
