### ISSUE TITLE
Configure a Container Registry in Nexus

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#4]
As an operator, I need to provide a service to store container images privately that are going to be generated by our CI pipelines in the ConverterService and ML Service repos.

**Acceptance Criteria:**
- The registry should be listening on port 5000.
- A new blob storage type "File" should be created just for this registry.
- The registry should be available at URL: https://registry.at04.devops.jala.university
- The registry should have a cleanup policy to remove container images older than 15 days at least.
- A new user should be created and granted with just the read and write permissions to push images in the registry.

**Dependency:**
This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/2

**Supporting docs:**
- https://www.sonatype.com/blog/using-sonatype-nexus-repository-3-part-3-docker-images

**Comment by calebespinoza** [comment]
@jessicaori Nexus has been deployed in Dev Server, so, you're able to start working on this item, will send you your user and password privately.

**Comment by jessicaori** [comment]
**Task progress:**
- Added port 5000 to map the nexus container
- Created a file blob store called docker-blob with a constraint limit of 20480MB
- Created the Cleaning Policy called docker-cleanup of docker format, to remove container images older than 15 days at least, and images that were not pulled in more than 30 days
- Created the at-registry repository in which the blob store 'docker-blob' and the cleaning policy 'docker-cleanup' were applied
- The registry is available at URL: https://nexus.at04.devops.jala.university/ (URL where the credentials were given)

**Pending for today:**
- A new user should be created and granted with just the read and write permissions to push images in the registry.
- The registry should be available at URL: https://registry.at04.devops.jala.university

**Comment by jessicaori** [comment]
@calebespinoza 
**Tasks completed:**
- Created the `nx-user` role with the add, edit, and read privilege for at-registry repository views
![Image](https://github.com/user-attachments/assets/7001c4ec-8209-4aca-a20f-622c2d1b8cda)
- Created and activated the `ci-user` ID user and assigned the `nx-user` role.
![Image](https://github.com/user-attachments/assets/4b5ede96-0c7d-477b-b0fa-6c8063656d7f)
- Tested the user by logging into the Docker registry and automating the process using `echo`.
![Image](https://github.com/user-attachments/assets/26ebbede-f03a-4aa4-9525-97b08a44abed)
