### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#9]
**Description:"
As an Operator, I need to share the knowledge about how the Ansible code works and how other team members can configure their local environments.

**Acceptance Criteria:**
- The information should be written in a Wiki in this repo.
- A README.md file should be created in the root of the repo.
- The README file should contain the steps to run the code locally (brief).

**Dependency:**
No dependencies.

**Comment by michelle-gh** [comment]
The readme file with a brief introduction to the project was added
In the wiki the following pages were created:
 * Home: General introduction and table of contents
 * Ansible configuration: About ansible and the specific ansible configuration for the project
 * Local configuration: Steps to configure the local environment
 * Run the project
